[workspace]
channels = ["conda-forge"]
name = "MuJoCo-Lab"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
uv = "*"
git = "*"  # git clone을 위해 추가

[tasks]
clone = "test -d mjlab || git clone https://github.com/mujocolab/mjlab.git"

setup = { depends-on = ["clone"], cmd = """
    cd mjlab && 
    uv sync && 
    uv add "mujoco-warp @ git+https://github.com/google-deepmind/mujoco_warp@1c6b31692eaa5d3134093958d839165245d196a6"
""" }